// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DBExecute(arg1, arg2) {
  return window['go']['main']['App']['DBExecute'](arg1, arg2);
}

export function DBSelect(arg1, arg2) {
  return window['go']['main']['App']['DBSelect'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MakeHttpRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MakeHttpRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
